import os
import json
import logging
from src.security import SecurityService

logger = logging.getLogger(__name__)

class SetupAssistant:
    """Interactive setup assistant to configure API keys, credentials, and settings securely."""

    @staticmethod
    def run_setup() -> None:
        print("\n==============================================")
        print("      Release Tracker: Interactive Setup      ")
        print("==============================================\n")
        
        # 1. TMDB API Key Prompt
        tmdb_key = input("Enter your TMDB API Key (or Bearer Token): ").strip()
        
        # 2. Google Calendar ID Prompt
        calendar_id = input("Enter your Google Calendar ID [default: primary]: ").strip() or "primary"
        
        # 3. Google Credentials JSON File Path Prompt
        creds_json = "{}"
        cred_path = input("Enter path to your Google Service Account JSON file (or press Enter to skip): ").strip()
        if cred_path:
            if os.path.exists(cred_path):
                with open(cred_path, "r", encoding="utf-8") as f:
                    creds_json = f.read().strip()
                print(f"[SUCCESS] Loaded Google credentials from '{cred_path}'.")
            else:
                print(f"[WARNING] File '{cred_path}' not found. Skipping live calendar auth for now.")

        # 4. Generate/Secure Encryption Key
        fernet_key = SecurityService()._key
        security = SecurityService(fernet_key)
        encrypted_tmdb = security.encrypt_data(tmdb_key) if tmdb_key else ""
        
        # 5. Write configuration to .env
        env_content = f"""# Automatically generated by setup assistant
ENCRYPTION_KEY={fernet_key}
TMDB_API_KEY_SECURE={encrypted_tmdb}
CALENDAR_ID={calendar_id}
GOOGLE_CREDENTIALS_JSON='{creds_json}'
DRY_RUN=true
ENABLE_CALENDAR_SYNC=true
ENABLE_GIT_COMMIT=false
ENABLE_API_FETCH=true
TIMEZONE=UTC
"""
        
        with open(".env", "w", encoding="utf-8") as f:
            f.write(env_content)
            
        print("\n[SUCCESS] Setup completed successfully! Configuration saved to '.env'.")

if __name__ == "__main__":
    SetupAssistant.run_setup()
        
