import os
import json
import logging
from src.security import SecurityService

logger = logging.getLogger(__name__)

class SetupAssistant:
    """Interactive setup assistant to configure API keys, credentials, and settings securely."""

    @staticmethod
    def run_setup() -> None:
        print("\n==============================================")
        print("      Release Tracker: Interactive Setup      ")
        print("==============================================\n")
        
        # 1. TMDB API Key Prompt
        print("The script uses the TMDB API to search for movies, TV series, and studios.")
        tmdb_key = input("Enter your TMDB API Key (or Bearer Token): ").strip()
        
        # 2. Google Calendar ID Prompt
        calendar_id = input("Enter your Google Calendar ID [default: primary]: ").strip() or "primary"
        
        # 3. Google Credentials JSON Prompt
        print("\nPaste your Google Service Account Credentials JSON content below (or press Enter to skip for dry-run):")
        creds_json = input("Google Credentials JSON: ").strip()
        if not creds_json:
            creds_json = "{}"
            print("No Google credentials provided. Running in dry-run/unauthenticated mode.")

        # 4. Generate/Secure Encryption Key
        fernet_key = SecurityService()._key
        security = SecurityService(fernet_key)
        
        # Encrypt sensitive tokens before storing in env/config
        encrypted_tmdb = security.encrypt_data(tmdb_key) if tmdb_key else ""
        
        # 5. Write configuration to .env
        env_content = f"""# Automatically generated by setup assistant
ENCRYPTION_KEY={fernet_key}
TMDB_API_KEY_SECURE={encrypted_tmdb}
CALENDAR_ID={calendar_id}
GOOGLE_CREDENTIALS_JSON='{creds_json}'
DRY_RUN=true
ENABLE_CALENDAR_SYNC=true
ENABLE_GIT_COMMIT=false
ENABLE_API_FETCH=true
TIMEZONE=UTC
"""
        
        with open(".env", "w", encoding="utf-8") as f:
            f.write(env_content)
            
        print("\n[SUCCESS] Setup completed successfully!")
        print("Configuration saved securely to '.env'. You can now run 'make sync-dry' or 'make add'.")

if __name__ == "__main__":
    SetupAssistant.run_setup()
    
